### ISSUE TITLE
Website is not build

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#1965]
I'm not sure why the website is not build the last step in RELEASE job on Azure look like this:

```yaml
      - script: npm run publish-website
        displayName: 'Update website'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          NPM_TOKEN: $(Npm.Token)

```

and it seems it got executed:

```
sitemap.js triggered...
Site built successfully. Generated files in 'build' folder.
nps is executing `website.publish` : (cd website && node ./scripts/deploy-gh-pages.cjs)

Finishing: Update website
```

But the website is not updated.

There are also two directories:

- website
- docs

I've tried to updated both
